CREATE TABLE PATIENTS
(
    PATIENT_ID int PRIMARY KEY NOT NULL IDENTITY,
    FIRST_NAME varchar(50) NOT NULL,
    MIDDLE_NAME varchar(50) NOT NULL,
    LAST_NAME varchar(50) NOT NULL,
    PHONE varchar(15)
);
CREATE UNIQUE INDEX Patients_ID_uindex ON PATIENTS (PATIENT_ID);

CREATE TABLE DOCTORS
(
    DOCTOR_ID int PRIMARY KEY NOT NULL IDENTITY,
    FIRST_NAME varchar(50) NOT NULL,
    MIDDLE_NAME varchar(50) NOT NULL,
    LAST_NAME varchar(50) NOT NULL,
    SPECIALIZATION varchar(25) NOT NULL
);
CREATE UNIQUE INDEX Doctors_ID_uindex ON DOCTORS (DOCTOR_ID);

CREATE TABLE RECIPES
(
    RECIPE_ID int PRIMARY KEY NOT NULL IDENTITY,
    DESCRIPTION varchar(200),
    PATIENT int NOT NULL,
    DOCTOR int NOT NULL,
    DATE_CREATE date,
    DURATION date,
    PRIORITY int,
    CONSTRAINT RECIPE_DOCTORS_ID_fk FOREIGN KEY (DOCTOR) REFERENCES DOCTORS (DOCTOR_ID),
    CONSTRAINT RECIPE_PATIENTS_ID_fk FOREIGN KEY (PATIENT) REFERENCES PATIENTS (PATIENT_ID)
);
CREATE UNIQUE INDEX Recipe_ID_uindex ON RECIPES (RECIPE_ID);